home/urls.py
from django.urls import path

from .views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

projeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from ninja import NinjaAPI

api = NinjaAPI(csrf=True, urls_namespace="api")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("api/", api.urls),
    path("", include("home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from projeto.urls import api

from .services.api import router
from .views import (
    CreateUsersView,
    ListUsersView,
    LoginView,
    RegisterView,
    UpdateUsersView,
)

api.add_router("users", router)

urlpatterns = [
    path("create/", CreateUsersView.as_view(), name="users-create"),
    path("<int:pk>/update/", UpdateUsersView.as_view(), name="users-update"),
    path("register/", RegisterView.as_view(), name="users-register"),
    path("", ListUsersView.as_view(), name="users-list"),
    path("login/", LoginView.as_view(), name="login"),
]

users/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from stdimage import StdImageField

from categorys.models import Category
from cities.models import City


def get_file_path(_instance, filename):
    """Function to get file path and generate unique name"""
    ext = filename.split(".")[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return filename


class CustomUserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError(_("The given email must be set"))

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        """
        Create common user
        """
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        """
        Create super user
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):

    PERSON_TYPES = (("P", _("Person")), ("C", _("Company")))

    email = models.EmailField(_("email address"), unique=True)
    full_name = models.CharField(_("full name"), max_length=120, null=True)
    document_number = models.CharField(_("document number"), max_length=14, null=True)
    person_type = models.CharField(
        _("person type"), max_length=2, choices=PERSON_TYPES, null=True
    )
    city = models.ForeignKey(
        City, on_delete=models.PROTECT, blank=False, null=True, verbose_name=_("city")
    )
    cellphone = models.CharField(_("cellphone"), max_length=15, null=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        blank=False,
        null=True,
        verbose_name=_("Category"),
    )
    image_profile = StdImageField(
        _("Image Profile"),
        upload_to=get_file_path,
        blank=True,
        default=None,
        variations={"thumb": {"width": 512, "height": 512, "crop": True}},
        delete_orphans=True,
    )
    # Add other fields as needed
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    last_login = models.DateTimeField(_("last login"), blank=True, null=True)
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    updated_at = models.DateTimeField(_("Updated At"), auto_now=True)

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def get_absolute_url(self):
        return reverse_lazy("users:detail", kwargs={"pk": self.pk})

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.full_name or self.email.split("@")[0]

templates/bases/base_create.html
{% extends '../bases/base_dashboard.html' %}
{% load static %}
{% load i18n %}

{% block main_container %}
  <div class="page-header">
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <div class="title">
          <h4>{% trans 'Create User' %}</h4>
        </div>
        <nav aria-label="breadcrumb" role="navigation">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'home' %}">{% trans 'Home' %}</a>
            </li>
            <li class="breadcrumb-item">
              <a href="{% url 'users-list' %}">{% trans 'Users' %}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              {% trans 'Create User' %}
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
{% endblock %}

{% block additional_scripts %}
  <script src="{% static 'src/plugins/jquery-Mask/jquery.mask.js' %}"></script>
  <script language="javascript">
    // Masks
    var cellphoneMask = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009'
      },
      spOptionsCellphone = {
        onKeyPress: function (val, e, field, options) {
          field.mask(cellphoneMask.apply({}, arguments), options)
        },
        placeholder: '(__) _________'
      }
    
    var documentNumberMask = function (val) {
      return val.replace(/\D/g, '').length <= 11 ? '000.000.000-000' : '00.000.000/0000-00'
    }
    spOptionsdocumentNumber = {
      onKeyPress: function (val, e, field, options) {
        field.mask(documentNumberMask.apply({}, arguments), options)
      }
    }
    
    $(document).ready(function () {
      $('#val').mask('000.000.000-00')
      $('#id_document_number').mask(documentNumberMask, spOptionsdocumentNumber)
      $('#nascimento').mask('00/00/0000')
      $('#telefone').mask(cellphoneMask, spOptionsCellphone)
      $('#telefone2').mask(cellphoneMask, spOptionsCellphone)
      $('#id_cellphone').mask(cellphoneMask, spOptionsCellphone)
      $('#id_phone').mask(cellphoneMask, spOptionsCellphone)
      $('#id_phonenumber').mask(cellphoneMask, spOptionsCellphone)
    })
  </script>
{% endblock %}

templates/bases/base_list.html
{% extends './base_dashboard.html' %}

{% load static %}
{% load i18n %}

{% block additional_scripts %}
  <!-- View modal -->
  <div class="col-md-4 col-sm-12 mb-30">
    <div class="modal fade" id="modal-view" tabindex="-1" role="dialog" aria-labelledby="myViewLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <script>
            $(document).on('click', '.view-item', function (e) {
              let itemId = $(this).data('id'); 
              createTable(itemId)
            })
          </script>
          <div class="modal-header">
            <h4 class="modal-title" id="myViewLabel">{% trans 'User Details' %}</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          </div>
          <div class="modal-body">
          <div id="tabela-container"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Close' %}</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End View modal -->
  <script>
    function createTable(id){
      $(document).ready(function() {
        // URL da API
        const apiUrl = `{% url 'api:users-list' %}?user_id=${id}`;

        // Fazendo a requisição
        $.get(apiUrl, function(data) {
            // Montando a tabela
            let tabelaHtml = `
                <table class="table table-bordered">
                    <tr>
                        <th>ID</th>
                        <td>${data.id}</td>
                    </tr>
                    <tr>
                        <th>Nome Completo</th>
                        <td>${data.full_name}</td>
                    </tr>
                    <tr>
                        <th>Número do Documento</th>
                        <td>${data.document_number}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>${data.email}</td>
                    </tr>
                    <tr>
                        <th>Celular</th>
                        <td>${data.cellphone}</td>
                    </tr>
                </table>
            `;

            // Inserindo a tabela no container
            $('#tabela-container').html(tabelaHtml);
        }).fail(function() {
            // Tratamento de erro
            $('#tabela-container').html('<p>Erro ao carregar os dados.</p>');
        });
    });
    }
  </script>

  <script>
    const API_DATA_LIST_URL = '{% url "users-list" %}?f=json'
  </script>
  <script src="{% static 'vendors/scripts/validators.js' %}"></script>

  <!-- Datatable Setting js -->
  <script src="{% static 'vendors/scripts/datatable-setting.js' %}"></script>
  <!-- add sweet alert js -->
  <script src="{% static 'src/plugins/sweetalert2/sweetalert2@11.js' %}"></script>
{% endblock %}